### ISSUE TITLE
Automate Mojo Marketplace Host Detection

### ISSUE THREAD

**Issue by rowdya22** [rowdya22/Quick-WP-CLI#4]
Currently there is no way to automatically detect which host the Mojo Marketplace plugin is installed on and it needs to be set manually. After speaking with a Mojo developer I learned that the brand is set manually across all automated installs. Until its automated we need to keep setting it manually.

**Comment by bvanfleet** [comment]
I agree with, and like the changes to the branding provided. I did make one modification regarding if users type with specific capitalization. The modification should address user input error. More details in the pull request #5

**Comment by rowdya22** [comment]
Where the Mojo Marketplace plugin can be installed on any WordPress site and any host, this feature will not be automated but will continue to present users with a list of choices. Not choosing a brand will default to Mojo Styling.
